config/routes.rb
Thingspeak::Application.routes.draw do

  # admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # main data posts using this route
  match 'update', :to => 'channels#post_data', :via => ((GET_SUPPORT) ? [:get, :post] : :post)
  match 's/update', :to => 'channels#post_data', :via => [:get, :post]

  # handle subdomain routes
  get '/', :to => 'subdomains#index', :constraints => { :subdomain => 'api' }
  get 'crossdomain', :to => 'subdomains#crossdomain', :constraints => { :subdomain => 'api' }

  root :to => 'pages#home'

  # for api: login and get token
  match 'users/api_login', :to => 'users#api_login', :via => [:get, :post]

  # devise for authentication
  # override devise controllers and use custom sessions_controller and registrations_controller
  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  resource :pages do
    collection do
      get :home
      get :about
      get :headers
      get :social_home
      post :contact_us
    end
  end

  match 'users/reset_password/:id', :to => 'users#reset_password', :as => 'reset_password', :via => [:get, :post]
  patch 'users/change_password/:id', :to => 'users#change_password'
  post 'mailer/resetpassword', :to => 'mailer#resetpassword'

  # public user profiles
  match 'account/edit_profile' => 'users#edit_profile', :as => 'edit_profile', :via => [:get, :post]
  patch 'account/update_profile' => 'users#update_profile', :as => 'update_profile'
  # users paths
  post 'users/new_api_key' => 'users#new_api_key', :as => 'user_new_api_key'
  get 'users/:id/channels(.:format)' => 'users#list_channels', :as => 'list_channels', :constraints => { :id => /.*/ }
  get 'users/:glob' => 'users#profile', :as => 'user_profile', :constraints => { :glob => /.*/ }

  resource :user_session
  resource 'account', :to => 'users'
  resources :users

  # social channels
  get 's/' => 'pages#social_home'
  get 's/:slug' => 'channels#social_show', :constraints => { :slug => /.*/ }
  get 'channels/social_new' => 'channels#social_new'

  # search
  resources :tags

  # specific feeds
  get 'channels/:channel_id/feed(s)(.:format)' => 'feed#index'
  get 'channels/:channel_id/field/:field_id(.:format)' => 'feed#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fields/:field_id(.:format)' => 'feed#index' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/field/:field_id/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/fields/:field_id/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/feed(s)/last_average(.:format)' => 'feed#last_average'
  get 'channels/:channel_id/feed(s)/last_median(.:format)' => 'feed#last_median'
  get 'channels/:channel_id/feed(s)/last_sum(.:format)' => 'feed#last_sum'
  get 'channels/:channel_id/feed/entry/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/feeds/entry/:id(.:format)' => 'feed#show' # not sure why this doesn't work with (s)
  get 'channels/:channel_id/social_feed' => 'channels#social_feed'
  get 'channels/:channel_id/feed(s)/debug' => 'feed#debug'
  delete 'channels/:id/feeds' => 'channels#clear'

  # maps
  get 'channels/:channel_id/maps/channel_show' => 'maps#channel_show'
  get 'channels/:channel_id/status/recent' => 'status#recent'

  # multiple series on a chart demo
  get 'charts/multiple_series' => 'charts#multiple_series'

  # nest the following controllers inside channels
  resources :channels do
    collection do
      get :public
      get :watched
      get :realtime
    end
    member do
      get :import
      post :upload
      post :clear
      put :watch
      post :realtime_update
    end
    resources :feed

    resources :feeds, :to => 'feed'
    resources :api_keys, :except => [:show, :edit]
    resources :status
    resources :statuses, :to => 'status'
    resources :charts
    resources :maps
    resources :channels
    resources :tags
    resources :comments
    resources :windows, :only => [:index, :update] do
      member do
        get :iframe
        get :html
        put :hide
        put :display
      end
    end
  end

  get 'channels/:channel_id/private_windows' => 'windows#private_windows'
  get 'channels/:channel_id/hidden_windows' => 'windows#hidden_windows'
  match 'channels/:channel_id/windows' => 'windows#update', :via => [:post, :put]

  resources :comments do
    member do
      post :vote
    end
  end

  resources :plugins do
    collection do
      get 'private_plugins'
      get 'public_plugins'
      #get 'public'
    end
  end

  resources :devices do
    member do
      get :thingtweet_arduino_code
      get :thingtweet_arduino_select_thingtweet
      post :add_mac_address
      put :ajax_update
    end
  end

  resources :pipes

  # twitter status update (version 1)
  match 'apps/thingtweet/1/statuses/update(.:format)' => 'thingtweets#update', :via => [:get, :post]
  match 'apps/thingtweet/1/statuses/update_debug(.:format)' => 'thingtweets#update_debug', :via => [:get, :post]


  # thinghttp action
  match 'apps/thinghttp/send_request' => 'thinghttp#send_request', :via => [:get, :post]

  # process responses for tweetcontrol
  match 'apps/tweetcontrol/process_response' => 'tweetcontrol#process_response', :via => [:get, :post]

  # apps and nested controllers
  scope 'apps' do
    resources :thingtweets do
      collection do
        get :authorize_response
      end
      member do
        put :new_api_key
      end
    end
    resources :thinghttp do
      resources :header
      member do
        put :new_api_key
      end
    end
    resources :talkbacks do
      member do
        put :new_api_key
      end
    end
    resources :tweetcontrol
    resources :reacts
    resources :timecontrols
  end

  # talkback api
  delete 'talkbacks/:talkback_id/commands', :to => 'commands#destroy_all'
  delete 'talkbacks/:talkback_id/commands/destroy_all', :to => 'commands#destroy_all'
  resources :talkbacks do
    resources :commands do
      collection do
        match :execute, :via => [:post, :get]
        delete :destroy_all
      end
    end
  end

  resources :apps, :only => ['index']

  # admin signups by day
  get 'admin/signups', :as => 'admin_signups', :to => 'admin/users#signups'
  # admin list of all email addresses
  get 'admin/emails', :as => 'admin_emails', :to => 'admin/users#emails'

  # app shortcuts
  get 'apps/thingtweet', :to => 'thingtweets#index'
  get 'apps/react', :to => 'react#index'

  # docs
  get 'docs(/:action)', :to => 'docs'

  # users
  devise_scope :user do
    match 'login', to: "devise/sessions#new", :via => [:get, :post]
    match 'logout', to: "devise/sessions#destroy", :via => [:get, :post]
  end

  # streaming routes
  match '/stream/channels/:id/feeds(.:format)', to: 'stream#channel_feed', :via => [:get, :post]

  # add support for CORS preflighting (matches any OPTIONS route up to 5 levels deep)
  # examples: /talkbacks, /talkbacks/4, /talkbacks/4/commands, /talkbacks/4/commands/6, /apps/thingtweet/1/statuses/update
  match '/:foo(/:foo(/:foo(/:foo(/:foo))))', :to => 'cors#preflight', :via => 'options'

  #match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/plugin.rb
# == Schema Information
#
# Table name: plugins
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  user_id     :integer
#  html        :text
#  css         :text
#  js          :text
#  created_at  :datetime
#  updated_at  :datetime
#  public_flag :boolean          default(FALSE)
#

class Plugin < ActiveRecord::Base
  belongs_to :user
  has_many :windows, -> { where window_type: 'plugin' }, :foreign_key => :content_id, :source => :window
  before_destroy { |record| record.windows.each { |window| window.delete } }

  # pagination variables
  cattr_reader :per_page
  @@per_page = 15

  # paginated hash for json and xml output
  # plugins input must be paginated
  def self.paginated_hash(plugins)
    {
      pagination:
      {
        current_page: plugins.current_page,
        per_page: plugins.per_page,
        total_entries: plugins.total_entries,
      },
      plugins: plugins.as_json(Plugin.public_options)
    }
  end

  # for to_json or to_xml, return only the public attributes
  def self.public_options
    {
      :root => false,
      :only => [:id, :name, :created_at, :public_flag],
      :methods => [:username, :url]
    }
  end

  # login name of the user who created the plugin
  def username; self.user.try(:login); end

  # url for the plugin
  def url
    domain = 'https://thingspeak.com'
    domain = 'http://staging.thingspeak.com' if Rails.env.staging?
    domain = 'http://127.0.0.1:3000' if Rails.env.development?
    return "#{domain}/plugins/#{self.id}"
  end

  def destroy_window
    window_id = Window.where(content_id: self.id, window_type: 'plugin').first.id
    Window.delete(window_id)
  end

  def public?; public_flag == true; end
  def private?; public_flag == false; end

  def has_private_windows(channel_id)
    has_private_windows = false
    windows.each do |window|

      if window.private? && window.channel_id == channel_id
        has_private_windows = true

      end

    end

    return has_private_windows
  end

  def has_public_windows(channel_id)
    has_public_windows = false
    windows.each do |window|
      has_public_windows = true if !window.private? && window.channel_id == channel_id
    end
    return has_public_windows
  end

  #private_dashboard_visibility
  def private_dashboard_windows(channel_id)
    dashboard_windows channel_id, true
  end

  def public_dashboard_windows(channel_id)
    dashboard_windows channel_id, false
  end
  def dashboard_windows(channel_id, privacy)
    dashboard_windows = []
    windows.each do |window|
      if window.private_flag == privacy && !window.show_flag && channel_id == window.channel_id
        dashboard_windows << window
      end
    end
    dashboard_windows
  end

  #public_dashboard_visibility
  def public_window
    public_window = nil
    windows.each do |window|
      if !window.private_flag # && !window.show_flag
        public_window = window
      end
    end
    unless public_window.nil?
      public_window
    else
      nil
    end
  end

  def make_windows(channel_id, api_domain)
    #create all the windows as appropriate
    #Private plugins have one window..
    #Public plugins have a private/private windows, private/public window and a public window
    if !has_public_windows(channel_id) && self.public?
      windows << Window.new_from(self, channel_id, :public, api_domain)
    else
      update_windows(channel_id)
    end

    if !has_private_windows(channel_id)
      windows << Window.new_from(self, channel_id, :private, api_domain)
    end
    save
  end

  def update_windows(channel_id)

    windows.each do |window|
      window.name = self.name
      window.save
    end

    if has_public_windows(channel_id) && self.private?
      windows.delete(public_window.destroy) unless public_window.nil?
    end

  end

  def update_all_windows
    channel_ids = Set.new
    windows.each do |window|
      window.name = self.name
      channel_ids.add( window.channel_id)
      window.save
    end
    channel_ids.each do |id|
      if has_public_windows(id) && self.private?
        windows.delete(public_window.destroy) unless public_window.nil?
      end
    end
  end

end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  before_filter :authenticate_via_api_key!, :only => [:index]
  before_filter :require_user, :except => [:show_public, :show, :public]
  before_filter :set_plugins_menu
  before_filter :check_permission, :only => ['edit', 'update', 'ajax_update', 'destroy']

  def check_permission
    @plugin = Plugin.find(params[:id])
    respond_with_error(:error_auth_required) and return if current_user.blank? || (@plugin.user_id != current_user.id)
  end

  def new; ; end
  def edit; ; end

  # get list of public plugins
  def public
    # error if page 0
    respond_with_error(:error_resource_not_found) and return if params[:page] == '0'

    # default blank response
    @plugins = Plugin.where(:id => 0).paginate :page => params[:page]

    # get plugins
    @plugins = Plugin.where("public_flag = true").order('updated_at DESC').paginate :page => params[:page]

    respond_to do |format|
      format.html
      format.json { render :json => Plugin.paginated_hash(@plugins).to_json }
      format.xml { render :xml => Plugin.paginated_hash(@plugins).to_xml(:root => 'response') }
    end
  end

  def index
    @plugins = current_user.plugins
    respond_to do |format|
      format.html
      format.json { render :json => @plugins.to_json(Plugin.public_options) }
      format.xml { render :xml => @plugins.to_xml(Plugin.public_options) }
    end
  end

  def public_plugins
    channel_id = params[:channel_id].to_i
    return if channel_id.nil?
    @plugin_windows = []
    plugins = current_user.plugins
    plugins.each do |plugin|
      plugin.make_windows channel_id, api_domain #will only make the window the first time
      @plugin_windows = @plugin_windows + plugin.public_dashboard_windows(channel_id)
    end

    respond_to do |format|
      format.html { render :partial => 'plugins' }
    end

  end

  def private_plugins
    channel_id = params[:channel_id].to_i
    return if channel_id.nil?
    #private page should display all plugins
    @plugin_windows = []

    plugins = current_user.plugins

    plugins.each do |plugin|
      plugin.make_windows channel_id, api_domain #will only make the window the first time
      @plugin_windows = @plugin_windows + plugin.private_dashboard_windows(channel_id)
    end
    respond_to do |format|
      format.html { render :partial => 'plugins' }
    end
  end

  def create
    # add plugin with defaults
    @plugin = Plugin.new

    # set default template
    template = 'default'

    # use case statement to set template, since user input is untrusted
    case params[:template]
    when 'gauge' then template = 'gauge'
    when 'chart' then template = 'chart'
    end

    # set template dynamically
    @plugin.html = read_file("app/views/plugins/templates/#{template}.html")
    @plugin.css = read_file("app/views/plugins/templates/#{template}.css")
    @plugin.js = read_file("app/views/plugins/templates/#{template}.js")

    @plugin.user_id = current_user.id
    @plugin.public_flag = false
    @plugin.save

    # now that the plugin is saved, we can create the default name
    @plugin.name = "#{t(:plugin_default_name)} #{@plugin.id}"
    @plugin.save

    # redirect to edit the newly created plugin
    redirect_to edit_plugin_path(@plugin.id)
  end

  def show
    @plugin = Plugin.find(params[:id])

    # make sure the user can access this plugin
    if (@plugin.private?)
      respond_with_error(:error_auth_required) and return if current_user.blank? || (@plugin.user_id != current_user.id)
    end

    @output = @plugin.html.sub('%%PLUGIN_CSS%%', @plugin.css).sub('%%PLUGIN_JAVASCRIPT%%', @plugin.js)

    render :layout => false
  end

  def show_public
    @plugin = Plugin.find(params[:id])
    @output = @plugin.html.sub('%%PLUGIN_CSS%%', @plugin.css).sub('%%PLUGIN_JAVASCRIPT%%', @plugin.js)
    if @plugin.private?
      render :layout => false
    else
      if request.url.include? 'api_domain'
        render :layout => false
      else

      redirect_to :host => api_domain,
            :controller => "plugins",
            :action => "show",
            :id => @plugin.id
      end
    end
  end

  def update
    @plugin.update_attribute(:name, params[:plugin][:name])
    @plugin.update_attribute(:public_flag, params[:plugin][:public_flag])
    @plugin.update_attribute(:css, params[:plugin][:css])
    @plugin.update_attribute(:js, params[:plugin][:js])
    @plugin.update_attribute(:html,params[:plugin][:html])

    if @plugin.save
      @plugin.update_all_windows
      flash[:notice] = I18n.t(:plugin_save_message)
      redirect_to edit_plugin_path(@plugin) and return
    end
  end

  def ajax_update
    status = 0
    @plugin.update_attribute(:name, params[:plugin][:name])
    @plugin.update_attribute(:public_flag, params[:plugin][:public_flag])
    @plugin.update_attribute(:css, params[:plugin][:css])
    @plugin.update_attribute(:js, params[:plugin][:js])
    @plugin.update_attribute(:html, params[:plugin][:html])

    if @plugin.save
      @plugin.update_all_windows
      status = 1
    end

    # return response: 1=success, 0=failure
    render :json => status.to_json
  end

  def destroy
    @plugin.destroy
    redirect_to plugins_path
  end
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/views/plugins/_plugins.html.erb
<% if @plugin_windows.blank? %>
<h4>All plugins are attached to a window.</h4>
<% else %>
<h4>Click a rectangle to view that Plugin in a dashboard window.</h4>
<% @plugin_windows.each do |plugin| %>
<div id="plugin-<%=plugin.id%>" class="ioplugin ui-widget-content addportlet"><%= plugin.name %></div>
<% end %>
<% end %>

app/views/plugins/edit.html.erb
<link href="//thingspeak.com/codemirror/codemirror.css" rel="stylesheet" />
<link href="//thingspeak.com/codemirror/neat.css" rel="stylesheet" />
<script type="text/javascript" src="//thingspeak.com/codemirror/codemirror.js"></script>
<script type="text/javascript" src="//thingspeak.com/codemirror/xml.js"></script>
<script type="text/javascript" src="//thingspeak.com/codemirror/javascript.js"></script>
<script type="text/javascript" src="//thingspeak.com/codemirror/css.js"></script>
<script type="text/javascript" src="//thingspeak.com/codemirror/htmlmixed.js"></script>

<style type="text/css">
  /* codemirror overrides */
  pre { overflow: inherit !important; }
  .activeline { background: #e8f2ff !important; }
  .CodeMirror { border: 1px solid #ccc; }
  .CodeMirror-scroll { height: 300px; }
</style>

<div class="col-sm-8 col-xs-12">

  <ol class="breadcrumb" data-no-turbolink>
    <li><%= link_to t(:plugins), plugins_path %></li>
    <li><%= link_to plugin_path(@plugin.id), target: '_blank' do %><%= t(:plugin) %> <%= @plugin.id %><% end %></li>
    <li class="active"><%= t(:edit) %></li>
  </ol>

  <%= form_for @plugin, :html => {:method => 'put', :class => 'form-horizontal'} do |c| %>
    <%= error_messages_for 'plugin', :header_message => t(:try_again), :message => t(:plugin_error) %>

    <div class="form-group">
      <label class="col-sm-2 col-xs-12 control-label"><%= t(:plugin_name) %></label>
      <div class="col-sm-10 col-xs-12"><%= c.text_field :name, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 col-xs-12 control-label"><%= t(:plugin_html) %></label>
      <div class="col-sm-10 col-xs-12"><%= c.text_area :html, :class => 'form-control', :rows => 14 %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 col-xs-12 control-label"><%= t(:plugin_css) %></label>
      <div class="col-sm-10 col-xs-12"><%= c.text_area :css, :class => 'form-control', :rows => 14 %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 col-xs-12 control-label"><%= t(:plugin_js) %></label>
      <div class="col-sm-10 col-xs-12"><%= c.text_area :js, :class => 'form-control', :rows => 14 %></div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10 col-xs-12">
        <div class="checkbox">
          <label>
            <%= c.check_box :public_flag %>
            <b><%= t(:plugin_public_flag) %></b>
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label"></label>
      <div class="col-sm-10"><p class="form-control-static"><%= c.submit t(:save_model, model: 'Plugin'), :class => 'btn btn-primary' %></p></div>
    </div>

  <% end %>

  <br><br>

  <h3><%= t(:plugin_delete_message) %></h3>
  <%= button_to t(:delete_model, model: 'Plugin'), plugin_path(@plugin.id), :method => 'delete', :data => { :confirm => t(:confirm_plugin_delete) }, :class => 'btn btn-danger' %>

</div>

<script type="text/javascript">

  // when document is ready
  $(document).on('page:load ready', function() {

    // set html codemirror
    var html_line = '';
    var html_editor = CodeMirror.fromTextArea(document.getElementById("plugin_html"), {
      lineNumbers: true,
      indentUnit: 2,
      extraKeys: {Tab: function(cm) { cm.replaceSelection("  ", "end"); }},
      matchBrackets: true,
      mode: "text/html",
      height: '300px',
      onCursorActivity: function() {
        html_editor.setLineClass(html_line, null, null);
        html_line = html_editor.setLineClass(html_editor.getCursor().line, null, "activeline");
      }
    });

    // set css codemirror
    var css_line = '';
    var css_editor = CodeMirror.fromTextArea(document.getElementById("plugin_css"), {
      lineNumbers: true,
      indentUnit: 2,
      extraKeys: {Tab: function(cm) { cm.replaceSelection("  ", "end"); }},
      matchBrackets: true,
      mode: "text/html",
      height: '300px',
      onCursorActivity: function() {
        css_editor.setLineClass(css_line, null, null);
        css_line = css_editor.setLineClass(css_editor.getCursor().line, null, "activeline");
      }
    });

    // set js codemirror
    var js_line = '';
    var js_editor = CodeMirror.fromTextArea(document.getElementById("plugin_js"), {
      lineNumbers: true,
      indentUnit: 2,
      extraKeys: {Tab: function(cm) { cm.replaceSelection("  ", "end"); }},
      matchBrackets: true,
      mode: "text/html",
      height: '300px',
      onCursorActivity: function() {
        js_editor.setLineClass(js_line, null, null);
        js_line = js_editor.setLineClass(js_editor.getCursor().line, null, "activeline");
      }
    });

    // clears status message
    function clearStatus() {
      setTimeout(function() {
        $('#status').html('');
      }, 2500);
    }

    // event to capture update button click
    $('#plugin_submit').click(
        function() {
      $.update(
        // url to post to
        '/plugins/ajax_update/<%= @plugin.id %>',

        // data to send
        {
          plugin:
          {
              name: $('#plugin_name').val(),
              public_flag: $('#plugin_public_flag').is(':checked'),
              html: $('#plugin_html').val(),
              css: $('#plugin_css').val(),
              js: $('#plugin_js').val()
          }
        },

        // if post was successful
        function (response) {
          var status = (response == '1') ? '<%= t(:saved) %>' : '<%= t(:saved_error) %>';
          $('#status').html(status);
          clearStatus();
        },

        // if post failed
        function (response) {
          $('#status').html('<%= t(:saved_error) %>');
          clearStatus();
        }
      );
      return false;
    });

  });
</script>

app/views/plugins/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6">

    <h4 class='breadcrumb'><%= t(:plugins) %></h4>

    <div class="col-pad">

      <%= link_to t(:new_model, model: 'Plugin'), new_plugin_path, class: 'btn btn-primary' %>
      <br><br>

      <% if @plugins.length > 0 %>
        <table class="table table-striped table-bordered tablesorter">
          <thead>
            <tr>
              <th><%= t(:plugin_name) %> <i class="fa fa-unsorted"></i></th>
                <th><%= t(:created) %> <i class="fa fa-unsorted"></i></td>
            </tr>
          </thead>
          <tbody>
            <% @plugins.each do |p| %>
            <tr>
              <td>
                <h4 style="margin-top: 0;">
                  <a href="<%= plugin_path(p.id) %>" target="_blank">
                    <i class="fa fa-<%= 'un' if p.public? %>lock fa-fw"></i>
                    <%= p.name %>
                  </a>
                </h4>
                <div class="btn-group btn-group-sm">
                  <%= link_to T(:view), plugin_path(p.id), :target => '_blank', class: 'btn btn-default' %>
                  <%= link_to T(:edit), edit_plugin_path(p.id), class: 'btn btn-default', 'data-no-turbolink' => 'true' %>
                </div>
              </td>
              <td><%= p.created_at.strftime("%Y-%m-%d") %></td>
            </tr>
            <% end %>
          </tbody>

        </table>
      <% end %>

    </div>
  </div>

  <div id="sidebar" class="col-xs-12 col-sm-6">
    <h4 class="breadcrumb"><%= t(:help) %></h4>

    <div class="col-pad">
      <%= t(:help_plugins) %>
      <ul>
        <li><a href="http://community.thingspeak.com/tutorials/google/display-a-google-gauge-visualization-using-thingspeak-plugins/" target="_blank">Google Gauge Tutorial</a></li>
      </ul>
    </div>
  </div>

</div>

app/views/plugins/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6">

    <ol class="breadcrumb">
      <li><%= link_to t(:plugins), plugins_path %></li>
      <li class="active"><%= t(:new) %></li>
    </ol>

    <div class="col-pad">
      <h3><%= t(:new_model, model: 'Plugin') %></h3>
      <br>
      <div><%= t(:plugin_new_message) %></div>
      <br>

      <%= form_for Plugin.new, :html => {:class => 'form-horizontal'} do |f| %>
        <div class="form-group">
          <label class="col-sm-3 col-xs-12 control-label"><%= t(:plugin_template) %></label>
          <div class="col-sm-9 col-xs-12">
            <div class="radio">
              <label>
                <%= radio_button_tag :template, 'default', :checked => 'checked' %> <%= T(:default) %>
              </label>
            </div>
            <div class="radio">
              <label>
                <%= radio_button_tag :template, 'gauge' %> Google Gauge
              </label>
            </div>
            <div class="radio">
              <label>
                <%= radio_button_tag :template, 'chart' %> <%= t(:plugin_chart) %>
              </label>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <p class="form-control-static">
              <%= f.submit t(:create_model, model: 'Plugin'), :class => 'btn btn-primary' %>
            </p>
          </div>
        </div>
      <% end %>
      <br>

    </div>
  </div>

  <div id="sidebar" class="col-xs-12 col-sm-6">
    <h4 class="breadcrumb"><%= t(:help) %></h4>

    <div class="col-pad">
      <%= t(:help_plugins) %>
      <ul>
        <li><a href="http://community.thingspeak.com/tutorials/google/display-a-google-gauge-visualization-using-thingspeak-plugins/" target="_blank">Google Gauge Tutorial</a></li>
      </ul>
    </div>
  </div>

</div>

app/views/plugins/public.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-9">
    <h4 class="breadcrumb">Plugins</h4>

    <% @plugins.each do |plugin| %>
      <div class="col-md-4 col-sm-6 col-xs-12">

        <div class="panel panel-primary">
          <div class="panel-heading">
            <%= link_to plugin_path(plugin.id), class: 'link-no-hover' do %>
              <i class="fa fa-plug"></i>
            <% end %>
            <%= link_to plugin_path(plugin.id) do %>
              <%= truncate(plugin.name, length: 23) %>
            <% end %>
          </div>

          <div class="panel-body">
            <p class="small">by <%= link_to(plugin.user.login, user_profile_path(plugin.user.login)) if plugin.user.present? %></p>
          </div>
        </div>

      </div>
    <% end %>

    <div class="clearfix"></div>
    <div class="col-pad">
      <%= will_paginate @plugins, renderer: BootstrapPagination::Rails %>
    </div>
  </div>

</div>

app/views/plugins/show.html.erb
<%= raw(@output) %>